---
# tasks file for base
- include: centos.yml
  when: ansible_os_family == 'RedHat' or ansible_distribution == 'Centos'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
