---
# tasks file for /Users/b8993513/workspace/ansible-demo/ansible/roles/firewall
- include: centos.yml
  when: ansible_os_family == 'RedHat' or ansible_distribution == 'Centos'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
