# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision :hosts do |provisioner|


end

config.vm.define "box" do |box|

    box.vm.box = "p0bailey/centos7.3"
    box.vm.network :private_network, ip: "192.168.56.4"
    box.vm.hostname = "centos7.3.local.com"
    box.ssh.insert_key = false

    box.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "1" ]
        v.customize [ "modifyvm", :id, "--memory", "512" ]
    end


#Ansible provisioner
    config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
end


#Shell provisioner to call a bash script.
#config.vm.provision "shell", path: "net.sh"

#This is required to fix a bug...
config.vm.provision "shell", inline: "sudo nmcli connection reload && sudo systemctl restart network.service"

end

 end
