---
galaxy_info:
  author: Phillip Bailey
  description: MongoDB installation and setup.
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - cloud
dependencies: []
